config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[show edit] do
    resources :chatrooms, only: :index, path: :inbox
  end

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :chatrooms, only: %i[show create] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :user_chatrooms, dependent: :destroy
  has_many :users, through: :user_chatrooms
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_chatrooms
  has_many :chatrooms, through: :user_chatrooms
  has_many :messages
end

app/models/user_chatroom.rb
class UserChatroom < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatroom = Chatroom.new
    @chatrooms = current_user.chatrooms
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @user = @chatroom.users.find { |user| user != current_user }
  end

  def create
    user = User.find(params[:user_id])

    if @chatroom = current_user.chatrooms.find { |chatroom| chatroom.users.include?(user) }
      redirect_to chatroom_path(@chatroom)
    else
      @chatroom = Chatroom.new(name: "#{user.email}")
      current_user.chatrooms << @chatroom
      user.chatrooms << @chatroom
      @chatroom.save
      InboxChannel.broadcast_to(
        user,
        render_to_string(partial: "chatrooms/chat_preview", locals: {chatroom: @chatroom})
      )
      redirect_to chatroom_path(@chatroom)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user

    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: 'message', locals: {message: @message})
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private
    def message_params
      params.require(:message).permit(:message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/_chat_preview.html.erb
<% if chatroom.users.any? { |user| user != current_user} %>
  <div data-inbox-target="inbox">
    <%= link_to content_tag("h2", chatroom.users.find { |user| user != current_user }.email), chatroom_path(chatroom) %>
      <%= render 'last_message', chatroom: chatroom %>
    </div>
<% end %>

app/views/chatrooms/_last_message.html.erb
<p data-inbox-target="lastMessage" data-chatroomid=<%=chatroom.id%>>
    <%= chatroom.messages.last.message if chatroom.messages.present? %>
</p>

app/views/chatrooms/index.html.erb
<div data-controller="inbox" data-inbox-userid-value=<%= current_user.id%>>
  <% @chatrooms.each do |chatroom| %>
      <%= render 'chat_preview', chatroom: chatroom %>
  <% end %>
</div>

<%= simple_form_for @chatroom, url: chatrooms_path do |f| %>
  <%= select_tag :user_id, options_from_collection_for_select(User.all, "id", "email") %>
  <%= f.submit "Start chat" %>
<% end %>

app/views/chatrooms/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
  <h1>#Conversation with <%= @user.email %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render 'messages/message', message: message  %>
    <% end %>
  </div>

  <%= simple_form_for [@chatroom, @message],
  html: {
    data: { action: "turbo:submit-end->chatroom-subscription#resetForm" },
    class: "d-flex"} do |f| %>
  <%= f.input :message,
    label: false,
    placeholder: "Message ##{@user.email}",
    wrapper_html: {class: "flex-grow-1"}
  %>
  <%= f.submit "Send", class: "btn btn-primary mb-3" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImpactarcNewApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
<p><%= message.message%></p>  </div>

app/views/pages/home.html.erb
<div data-controller="home">
  <p data-home-target="something">Weird</p>
  <button data-action="click->home#printToConsole">Click me</button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", user_chatrooms_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>